### ISSUE TITLE
Directed graphs

### ISSUE THREAD

**Issue by briatte** [alessandrobessi/disparityfilter#1]
Dear @alessandrobessi 

Are you certain that this is how the algorithm should be implemented for directed networks? I'm looking at [the original paper](http://arxiv.org/pdf/0904.2389v1.pdf), and the appendix seems to suggest differently.

**Comment by alessandrobessi** [comment]
I didn't see the arXiv preprint version, but it looks a bit different from the paper published on PNAS! Maybe the authors changed something following some reviewer's suggestions...

-A

**Comment by briatte** [comment]
Thanks for the quick reply.

The [appendix of the published version](http://www.pnas.org/content/suppl/2009/04/03/0808904106.DCSupplemental/Appendix_PDF.pdf) seems quite similar to the appendix of the preprint to me.

I don't think it would be that difficult to support directed networks: if I understand Serrano _et al._ correctly, on a directed network, the algorithm just needs to run twice, once on in-links (using the in-degree distribution for the null model), and a second time using out-links (using the out-degree distribution for the null model). The backbone is the sum of the links selected by any of the runs.

Your algorithm works perfectly for undirected networks, so there's nothing to change there. I've [rewritten your code](https://gist.github.com/briatte/ee36be88739ec09ce3ec) using native `igraph` functions, but my version is slower than yours.

Let me know if you are interested in supporting directed networks, in which case I will give some thought to how it might be done.

**Comment by alessandrobessi** [comment]
of course I'm interested :) let me know your thoughts

On Sun, Oct 4, 2015 at 12:23 AM, François Briatte <notifications@github.com>
wrote:

> Thanks for the quick reply.
>
> The appendix of the published version
> <http://www.pnas.org/content/suppl/2009/04/03/0808904106.DCSupplemental/Appendix_PDF.pdf>
> seems quite similar to the appendix of the preprint to me.
>
> I don't think it would be that difficult to support directed networks: if
> I understand Serrano *et al.* correctly, on a directed network, the
> algorithm just needs to run twice, once on in-links (using the in-degree
> distribution for the null model), and a second time using out-links (using
> the out-degree distribution for the null model). The backbone is the sum of
> the links selected by any of the runs.
>
> Your algorithm works perfectly for undirected networks, so there's nothing
> to change there. I've rewritten your code
> <https://gist.github.com/briatte/ee36be88739ec09ce3ec> using native igraph
> functions, but my version is slower than yours.
>
> Let me know if you are interested in supporting directed networks, in
> which case I will give some thought to how it might be done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alessandrobessi/disparityfilter/issues/1#issuecomment-145295136>
> .
>



-- 
*Alessandro Bessi*

Mobile: +39.3313427237
Twitter: @ibbessi <https://twitter.com/ibbessi>
Web: http://www.alessandrobessi.org

**Comment by briatte** [comment]
The appendix seems to say that, on a directed graph, there's just twice more work to do, because there's two degree distributions. So all we need, really, is this:

```R
backbone <- function(graph, weights = NULL, directed = is_directed(graph),
                     alpha = 0.05) {

  if (!igraph::is_igraph(graph)) {
    stop("Not a graph object")
  }

  if (is.null(weights) && "weight" %in% igraph::edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  stopifnot(!is.null(weights))

  if (!directed) {
    b = disparity_filter(graph, weights, "all", alpha)
  } else {
    b = rbind(
      disparity_filter(graph, weights, "in", alpha),
      disparity_filter(graph, weights, "out", alpha)
    )
  }
  return(unique(b[ order(b$from), ]))

}
```

The `backbone` function calls the disparity filter once if the graph is undirected, twice if it is directed (first on the in-degree distribution, then on the out-degree one). The rest of the code above imitates how `igraph` works with weighted graphs (see e.g. `constraint` or `modularity`).

Here's the disparity filter, adapted to work with both undirected and directed degree distributions and ego networks. Uncomment the `### cat` line to get verbose results:

```R
disparity_filter <- function(G, weights, mode = "all", alpha = 0.05) {

  d = igraph::degree(G, mode = mode)
  e = cbind(igraph::as_data_frame(G)[, 1:2 ], weight = weights, alpha = NA)

  for (u in which(d > 1)) {

    if (mode == "all") {
      sum_w = sum(e$weight[ which(e[, 1] == u | e[, 2] == u) ])
    } else if (mode == "in") {
      sum_w = sum(e$weight[ which(e[, 2] == u) ])
    } else if (mode == "out") {
      sum_w = sum(e$weight[ which(e[, 1] == u) ])
    }

    for (v in igraph::ego(G, 1, u, mode)[[1]][-1]) {

      if (mode == "all") {        
        ij = which((e[, 1] == u & e[, 2] == v) | (e[, 1] == v & e[, 2] == u))
      } else if (mode == "in") {
        ij = which((e[, 1] == v & e[, 2] == u))
      } else if (mode == "out") {
        ij = which((e[, 1] == u & e[, 2] == v))
      }
      ### cat(mode, "-", u, "->", v, ":", ij, "\n")
      
      p_ij = e$weight[ ij ] / sum_w
      
      # alpha_ij = integrate(function(x) { (1 - x) ^ (d[u] - 2) }, 0, p_ij)
      # alpha_ij = 1 - (d[u] - 1) * alpha_ij$value
      e$alpha[ ij ] = (1 - p_ij) ^ (d[u] - 1)

    }

  }
  
  return(unique(e[ !is.na(e$alpha) & e$alpha < alpha, 1:3 ]))

}
```

I'm testing the code right now. Perhaps the `if` … `else` statements can be coded more efficiently as `switch` statements.

Let me know what you think!

**Comment by alessandrobessi** [comment]
It looks fine to me!

I replaced if/else statements with switch statements.

PS. you have a nice GitHub profile and coding skills :) we should work
together on other networks-related algorithms :)



disparity_filter <- function(G, weights, mode = "all", alpha = 0.05) {

  d = igraph::degree(G, mode = mode)
  e = cbind(igraph::as_data_frame(G)[, 1:2 ], weight = weights, alpha = NA)

  for (u in which(d > 1)) {

    switch(mode,
           all = {sum_w = sum(e$weight[ which(e[, 1] == u | e[, 2] == u)
])},
           in = {sum_w = sum(e$weight[ which(e[, 2] == u) ])},
           out = {sum_w = sum(e$weight[ which(e[, 1] == u) ])}
           )

    for (v in igraph::ego(G, 1, u, mode)[[1]][-1]) {

      switch(mode,
             all = {ij = which((e[, 1] == u & e[, 2] == v) | (e[, 1] == v &
e[, 2] == u))},
             in = {ij = which((e[, 1] == v & e[, 2] == u))},
             out = {ij = which((e[, 1] == u & e[, 2] == v))}
             )

      ### cat(mode, "-", u, "->", v, ":", ij, "\n")

      p_ij = e$weight[ ij ] / sum_w

      # alpha_ij = integrate(function(x) { (1 - x) ^ (d[u] - 2) }, 0, p_ij)
      # alpha_ij = 1 - (d[u] - 1) * alpha_ij$value
      e$alpha[ ij ] = (1 - p_ij) ^ (d[u] - 1)

    }

  }

  return(unique(e[ !is.na(e$alpha) & e$alpha < alpha, 1:3 ]))

}

On Sun, Oct 4, 2015 at 3:29 PM, François Briatte <notifications@github.com>
wrote:

> The appendix seems to say that, on a directed graph, there's just twice
> more work to do, because there's two degree distributions. So all we need,
> really, is this:
>
> backbone <- function(graph, weights = NULL, directed = is_directed(graph),
>                      alpha = 0.05) {
>
>   if (!igraph::is_igraph(graph)) {
>     stop("Not a graph object")
>   }
>
>   if (is.null(weights) && "weight" %in% igraph::edge_attr_names(graph)) {
>     weights <- E(graph)$weight
>   }
>   stopifnot(!is.null(weights))
>
>   if (!directed) {
>     b = disparity_filter(graph, weights, "all", alpha)
>   } else {
>     b = rbind(
>       disparity_filter(graph, weights, "in", alpha),
>       disparity_filter(graph, weights, "out", alpha)
>     )
>   }
>   return(unique(b[ order(b$from), ]))
>
> }
>
> The backbone function calls the disparity filter once if the graph is
> undirected, twice if it is directed (first on the in-degree distribution,
> then on the out-degree one). The rest of the code above imitates how
> igraph works with weighted graphs (see e.g. constraint or modularity).
>
> Here's the disparity filter, adapted to work with both undirected and
> directed degree distributions and ego networks. Uncomment the ### cat
> line to get verbose results:
>
> disparity_filter <- function(G, weights, mode = "all", alpha = 0.05) {
>
>   d = igraph::degree(G, mode = mode)
>   e = cbind(igraph::as_data_frame(G)[, 1:2 ], weight = weights, alpha = NA)
>
>   for (u in which(d > 1)) {
>
>     if (mode == "all") {
>       sum_w = sum(e$weight[ which(e[, 1] == u | e[, 2] == u) ])
>     } else if (mode == "in") {
>       sum_w = sum(e$weight[ which(e[, 2] == u) ])
>     } else if (mode == "out") {
>       sum_w = sum(e$weight[ which(e[, 1] == u) ])
>     }
>
>     for (v in igraph::ego(G, 1, u, mode)[[1]][-1]) {
>
>       if (mode == "all") {
>         ij = which((e[, 1] == u & e[, 2] == v) | (e[, 1] == v & e[, 2] == u))
>       } else if (mode == "in") {
>         ij = which((e[, 1] == v & e[, 2] == u))
>       } else if (mode == "out") {
>         ij = which((e[, 1] == u & e[, 2] == v))
>       }
>       ### cat(mode, "-", u, "->", v, ":", ij, "\n")
>
>       p_ij = e$weight[ ij ] / sum_w
>
>       # alpha_ij = integrate(function(x) { (1 - x) ^ (d[u] - 2) }, 0, p_ij)
>       # alpha_ij = 1 - (d[u] - 1) * alpha_ij$value
>       e$alpha[ ij ] = (1 - p_ij) ^ (d[u] - 1)
>
>     }
>
>   }
>
>   return(unique(e[ !is.na(e$alpha) & e$alpha < alpha, 1:3 ]))
>
> }
>
> I'm testing the code right now. Perhaps the if … else statements can be
> coded more efficiently as switch statements.
>
> Let me know what you think!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alessandrobessi/disparityfilter/issues/1#issuecomment-145350396>
> .
>



-- 
*Alessandro Bessi*

Mobile: +39.3313427237
Twitter: @ibbessi <https://twitter.com/ibbessi>
Web: http://www.alessandrobessi.org

**Comment by briatte** [comment]
I've [updated my Gist](https://gist.github.com/briatte/ee36be88739ec09ce3ec) with the fastest and cleanest code that I could write. It now takes less than 10 seconds to reproduce the Python example.

What would you think of submitting the code for inclusion in the `igraph` package? Gabor Csardi might even be able to speed it up by calling some C equivalents.

**Comment by briatte** [comment]
P.S. I'm also OK with updating your package if you prefer that option.

P.S. 2. Thanks for the compliment, and sure, let me know if you find other network algorithms to implement!

**Comment by alessandrobessi** [comment]
I'm fine with asking Gabor Csardi to implement it into igraph!

-A

**Comment by alessandrobessi** [comment]
Gabor Csardi does not seem much interested :)

On Sun, Oct 4, 2015 at 6:54 PM, François Briatte <notifications@github.com>
wrote:

> P.S. I'm also OK with updating your package if you prefer that option.
>
> P.S. 2. Thanks for the compliment, and sure, let me know if you find other
> network algorithms to implement!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alessandrobessi/disparityfilter/issues/1#issuecomment-145366114>
> .
>



-- 
*Alessandro Bessi*

Mobile: +39.3313427237
Twitter: @ibbessi <https://twitter.com/ibbessi>
Web: http://www.alessandrobessi.org

**Comment by alessandrobessi** [comment]
HI Francois, do you want to update the disparityfilter package on CRAN?

**Comment by briatte** [comment]
Just submitted #2 to do so. Closing this thread.
